website:
  urls: https://ikman.lk/en/ads/sri-lanka/vehicles?sort=relevance&buy_now=0&urgent=0&query=,https://riyasewana.com/search/,https://autobid.de/?action=auctions


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


application:
  security:
    jwt:
      secret-key: 8f15bbfdd567e137221779f4c16a58b9314d0360f7c520b7ad390a226eb027a0
      expiration: 18000000 # 5 hours

server:
  port: 8081
  tomcat:
    threads:
      max: 100


