website:
  urls: https://ikman.lk/en/ads/sri-lanka/vehicles?sort=relevance&buy_now=0&urgent=0&query=,https://riyasewana.com/search/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


#  datasource:
#    url: jdbc:clickhouse://localhost:8123/test
#    username: andimus
#    password: root
#    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    open-in-view: false
#    database-platform: org.hibernate.dialect.ClickHouseDialect
